"""
GENESIS MODULE v1.0 - Capacite d'Auto-Coding
Genere des scripts Python a la volee via M2 GPT-OSS
Securite: sandbox dans scripts/generated/, jamais d'execution auto sans confirmation
"""
import os
import time
import json
import requests

ROOT = r"F:\BUREAU\TRADING_V2_PRODUCTION"
SCRIPTS_DIR = os.path.join(ROOT, "scripts")
GENERATED_DIR = os.path.join(SCRIPTS_DIR, "generated")
M2_URL = "http://192.168.1.26:1234/v1/chat/completions"
M2_MODEL = "openai/gpt-oss-20b"
M2_TIMEOUT = 60


def generate_tool(description, filename=None):
    """Genere un script Python a partir d'une description en langage naturel"""
    if not filename:
        filename = f"tool_{int(time.time())}.py"
    if not filename.endswith('.py'):
        filename += '.py'

    os.makedirs(GENERATED_DIR, exist_ok=True)
    filepath = os.path.join(GENERATED_DIR, filename)

    print(f"  GENESIS: Creation de '{filename}'...")
    print(f"  Description: {description}")

    prompt = f"""Ecris un script Python complet et fonctionnel pour Windows.
DEMANDE: "{description}"

CONTRAINTES:
1. Utilise les libs standards (os, sys, shutil, glob, pathlib, subprocess, json, time, datetime)
2. Ou libs courantes: pyautogui, psutil, requests
3. Le code doit etre autonome avec if __name__ == "__main__":
4. Gere les erreurs avec try/except
5. Ajoute des print() pour le feedback
6. Ecris UNIQUEMENT le code Python, pas de markdown, pas d'explication

CODE PYTHON:"""

    try:
        payload = {
            "model": M2_MODEL,
            "messages": [
                {"role": "system", "content": "Tu es un developpeur Python Senior. Ecris du code propre, fonctionnel et securise. UNIQUEMENT du code Python, rien d'autre."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.2,
            "max_tokens": 2000
        }
        t0 = time.time()
        r = requests.post(M2_URL, json=payload, timeout=M2_TIMEOUT)
        latency = time.time() - t0

        if r.status_code != 200:
            return None, f"M2 HTTP {r.status_code}"

        msg = r.json()['choices'][0]['message']
        content = msg.get('content', '') or ''
        if not content.strip():
            content = msg.get('reasoning_content', '') or msg.get('reasoning', '') or ''

        # Nettoyage du code
        code = content.strip()
        if code.startswith("```python"):
            code = code[len("```python"):].strip()
        if code.startswith("```"):
            code = code[3:].strip()
        if code.endswith("```"):
            code = code[:-3].strip()
        # GPT-OSS special tokens cleanup
        import re
        code = re.sub(r'<\|[^|]*\|>[^<\n]*(?:<\|[^|]*\|>)?', '', code).strip()

        # Ecrire le fichier
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(f'# Auto-generated by GENESIS @ {time.strftime("%Y-%m-%d %H:%M:%S")}\n')
            f.write(f'# Description: {description}\n\n')
            f.write(code)

        lines = code.count('\n') + 1
        print(f"  GENESIS OK: {filepath} ({lines} lignes, {latency:.1f}s)")
        return filepath, None

    except requests.exceptions.Timeout:
        return None, f"M2 timeout ({M2_TIMEOUT}s)"
    except Exception as e:
        return None, str(e)


def list_generated():
    """Liste les outils generes"""
    if not os.path.exists(GENERATED_DIR):
        return []
    files = [f for f in os.listdir(GENERATED_DIR) if f.endswith('.py')]
    files.sort(key=lambda f: os.path.getmtime(os.path.join(GENERATED_DIR, f)), reverse=True)
    return files


if __name__ == "__main__":
    print("=== GENESIS MODULE - TEST ===")
    filepath, err = generate_tool(
        "Liste les 5 plus gros fichiers du dossier F:\\BUREAU et affiche leur taille en MB",
        "disk_analyzer.py"
    )
    if filepath:
        print(f"\nGenere: {filepath}")
        print("\nContenu:")
        with open(filepath, 'r', encoding='utf-8') as f:
            print(f.read())
    else:
        print(f"Erreur: {err}")
