#!/usr/bin/env python3
"""Insere 100 commandes vocales avancees dans jarvis.db (10 domaines x 10 commandes)."""

import json
import sqlite3
import time

DB_PATH = "/home/turbo/jarvis/data/jarvis.db"

# 100 commandes vocales avancees organisees par domaine
ADVANCED_COMMANDS = [
    # ── 1. Gestion des fenetres avancee (10) ──
    {
        "name": "adv_win_snap_left",
        "category": "advanced_windows",
        "description": "Place la fenetre active a gauche de l'ecran",
        "triggers": ["mets cette fenêtre à gauche", "fenêtre à gauche", "snap gauche"],
        "action_type": "bash",
        "action": "wmctrl -r :ACTIVE: -e 0,0,0,$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f1 | awk '{print int($1/2)}'),$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f2 | awk '{print int($1)}')",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_snap_right",
        "category": "advanced_windows",
        "description": "Place la fenetre active a droite de l'ecran",
        "triggers": ["mets cette fenêtre à droite", "fenêtre à droite", "snap droite"],
        "action_type": "bash",
        "action": "wmctrl -r :ACTIVE: -e 0,$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f1 | awk '{print int($1/2)}'),0,$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f1 | awk '{print int($1/2)}'),$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f2 | awk '{print int($1)}')",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_fullscreen",
        "category": "advanced_windows",
        "description": "Met la fenetre active en plein ecran",
        "triggers": ["fenêtre plein écran", "plein écran", "fullscreen", "maximise la fenêtre"],
        "action_type": "bash",
        "action": "wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_restore",
        "category": "advanced_windows",
        "description": "Restaure la fenetre active a sa taille normale",
        "triggers": ["restaure la fenêtre", "taille normale", "unmaximize"],
        "action_type": "bash",
        "action": "wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_minimize",
        "category": "advanced_windows",
        "description": "Minimise la fenetre active",
        "triggers": ["minimise la fenêtre", "réduis la fenêtre", "minimize"],
        "action_type": "bash",
        "action": "xdotool getactivewindow windowminimize",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_close_all",
        "category": "advanced_windows",
        "description": "Ferme toutes les fenetres ouvertes",
        "triggers": ["ferme toutes les fenêtres", "ferme tout", "close all windows"],
        "action_type": "bash",
        "action": "wmctrl -l | awk '{print $1}' | xargs -I{} wmctrl -ic {}",
        "params": "[]",
        "confirm": 1,
    },
    {
        "name": "adv_win_list_all",
        "category": "advanced_windows",
        "description": "Liste toutes les fenetres ouvertes",
        "triggers": ["liste les fenêtres", "fenêtres ouvertes", "list windows"],
        "action_type": "bash",
        "action": "wmctrl -l",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_always_on_top",
        "category": "advanced_windows",
        "description": "Garde la fenetre active toujours au premier plan",
        "triggers": ["fenêtre toujours devant", "always on top", "premier plan"],
        "action_type": "bash",
        "action": "wmctrl -r :ACTIVE: -b toggle,above",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_tile_mosaic",
        "category": "advanced_windows",
        "description": "Arrange toutes les fenetres en mosaique",
        "triggers": ["toutes les fenêtres en mosaïque", "mosaïque", "tile windows"],
        "action_type": "bash",
        "action": "wmctrl -l | awk '{print $1}' | while read wid; do wmctrl -ir $wid -b remove,maximized_vert,maximized_horz; done && echo 'Fenetres arrangees en mosaique'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_win_move_center",
        "category": "advanced_windows",
        "description": "Centre la fenetre active sur l'ecran",
        "triggers": ["centre la fenêtre", "fenêtre au centre", "center window"],
        "action_type": "bash",
        "action": "wmctrl -r :ACTIVE: -e 0,$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f1 | awk '{print int($1/4)}'),$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f2 | awk '{print int($1/4)}'),$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f1 | awk '{print int($1/2)}'),$(xdpyinfo | grep dimensions | awk '{print $2}' | cut -dx -f2 | awk '{print int($1/2)}')",
        "params": "[]",
        "confirm": 0,
    },

    # ── 2. Applications courantes (10) ──
    {
        "name": "adv_app_spotify",
        "category": "advanced_apps",
        "description": "Lance Spotify",
        "triggers": ["ouvre spotify", "lance spotify", "spotify"],
        "action_type": "bash",
        "action": "spotify &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_discord",
        "category": "advanced_apps",
        "description": "Lance Discord",
        "triggers": ["ouvre discord", "lance discord", "discord"],
        "action_type": "bash",
        "action": "discord &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_steam",
        "category": "advanced_apps",
        "description": "Lance Steam",
        "triggers": ["ouvre steam", "lance steam", "steam"],
        "action_type": "bash",
        "action": "steam &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_gimp",
        "category": "advanced_apps",
        "description": "Lance GIMP",
        "triggers": ["ouvre gimp", "lance gimp", "gimp"],
        "action_type": "bash",
        "action": "gimp &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_libreoffice",
        "category": "advanced_apps",
        "description": "Lance LibreOffice",
        "triggers": ["ouvre libre office", "lance libreoffice", "libre office"],
        "action_type": "bash",
        "action": "libreoffice &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_vlc",
        "category": "advanced_apps",
        "description": "Lance VLC media player",
        "triggers": ["ouvre vlc", "lance vlc", "vlc"],
        "action_type": "bash",
        "action": "vlc &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_thunderbird",
        "category": "advanced_apps",
        "description": "Lance Thunderbird email",
        "triggers": ["ouvre thunderbird", "lance thunderbird", "ouvre les mails"],
        "action_type": "bash",
        "action": "thunderbird &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_obs",
        "category": "advanced_apps",
        "description": "Lance OBS Studio",
        "triggers": ["ouvre obs", "lance obs studio", "obs studio"],
        "action_type": "bash",
        "action": "obs &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_vscode",
        "category": "advanced_apps",
        "description": "Lance Visual Studio Code",
        "triggers": ["ouvre vscode", "lance vscode", "visual studio code", "ouvre l'éditeur"],
        "action_type": "bash",
        "action": "code &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_app_nautilus",
        "category": "advanced_apps",
        "description": "Lance le gestionnaire de fichiers",
        "triggers": ["ouvre le gestionnaire de fichiers", "fichiers", "nautilus", "explorateur de fichiers"],
        "action_type": "bash",
        "action": "nautilus &>/dev/null &",
        "params": "[]",
        "confirm": 0,
    },

    # ── 3. Gestion fichiers avancee (10) ──
    {
        "name": "adv_files_find_large",
        "category": "advanced_files",
        "description": "Trouve les fichiers de plus de 100 Mo",
        "triggers": ["trouve les gros fichiers", "gros fichiers", "fichiers volumineux"],
        "action_type": "bash",
        "action": "find /home/turbo -type f -size +100M -exec ls -lh {} \\; 2>/dev/null | sort -k5 -h | tail -20",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_recent",
        "category": "advanced_files",
        "description": "Liste les fichiers modifies dans les dernieres 24h",
        "triggers": ["derniers fichiers modifiés", "fichiers récents", "fichiers modifiés aujourd'hui"],
        "action_type": "bash",
        "action": "find /home/turbo -type f -mtime -1 -not -path '*/\\.*' 2>/dev/null | head -30",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_disk_by_folder",
        "category": "advanced_files",
        "description": "Affiche l'espace utilise par dossier",
        "triggers": ["espace par dossier", "taille des dossiers", "espace disque par dossier"],
        "action_type": "bash",
        "action": "du -sh /home/turbo/*/ 2>/dev/null | sort -h",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_duplicates",
        "category": "advanced_files",
        "description": "Cherche les fichiers dupliques dans le dossier personnel",
        "triggers": ["fichiers dupliqués", "doublons", "trouve les doublons"],
        "action_type": "bash",
        "action": "fdupes -r /home/turbo/Documents 2>/dev/null | head -50 || echo 'Installez fdupes: sudo apt install fdupes'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_empty",
        "category": "advanced_files",
        "description": "Trouve les fichiers vides",
        "triggers": ["fichiers vides", "trouve les fichiers vides", "empty files"],
        "action_type": "bash",
        "action": "find /home/turbo -type f -empty -not -path '*/\\.*' 2>/dev/null | head -30",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_empty_dirs",
        "category": "advanced_files",
        "description": "Trouve les dossiers vides",
        "triggers": ["dossiers vides", "trouve les dossiers vides", "répertoires vides"],
        "action_type": "bash",
        "action": "find /home/turbo -type d -empty -not -path '*/\\.*' 2>/dev/null | head -30",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_count_by_type",
        "category": "advanced_files",
        "description": "Compte les fichiers par extension",
        "triggers": ["fichiers par type", "compte les fichiers par extension", "types de fichiers"],
        "action_type": "bash",
        "action": "find /home/turbo -type f -not -path '*/\\.*' 2>/dev/null | sed 's/.*\\.//' | sort | uniq -c | sort -rn | head -20",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_oldest",
        "category": "advanced_files",
        "description": "Trouve les fichiers les plus anciens",
        "triggers": ["fichiers les plus anciens", "vieux fichiers", "oldest files"],
        "action_type": "bash",
        "action": "find /home/turbo -type f -not -path '*/\\.*' -printf '%T+ %p\\n' 2>/dev/null | sort | head -20",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_symlinks",
        "category": "advanced_files",
        "description": "Liste les liens symboliques",
        "triggers": ["liens symboliques", "symlinks", "liste les liens"],
        "action_type": "bash",
        "action": "find /home/turbo -type l -not -path '*/\\.*' 2>/dev/null | head -30",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_files_permissions",
        "category": "advanced_files",
        "description": "Trouve les fichiers avec permissions larges",
        "triggers": ["fichiers avec permissions larges", "fichiers world writable", "permissions ouvertes"],
        "action_type": "bash",
        "action": "find /home/turbo -type f -perm -o+w -not -path '*/\\.*' 2>/dev/null | head -20",
        "params": "[]",
        "confirm": 0,
    },

    # ── 4. Systeme avance (10) ──
    {
        "name": "adv_sys_cpu_load",
        "category": "advanced_system",
        "description": "Affiche la charge CPU detaillee",
        "triggers": ["charge cpu", "charge processeur", "cpu load", "utilisation cpu"],
        "action_type": "bash",
        "action": "mpstat -P ALL 1 1 2>/dev/null || top -bn1 | head -5",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_proc_by_mem",
        "category": "advanced_system",
        "description": "Liste les processus tries par memoire",
        "triggers": ["processus par mémoire", "top mémoire", "processus gourmands en ram"],
        "action_type": "bash",
        "action": "ps aux --sort=-%mem | head -15",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_proc_by_cpu",
        "category": "advanced_system",
        "description": "Liste les processus tries par CPU",
        "triggers": ["processus par cpu", "top cpu", "processus gourmands en cpu"],
        "action_type": "bash",
        "action": "ps aux --sort=-%cpu | head -15",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_temperatures",
        "category": "advanced_system",
        "description": "Affiche toutes les temperatures du systeme",
        "triggers": ["températures", "temperatures", "température système", "sensors"],
        "action_type": "bash",
        "action": "sensors 2>/dev/null || echo 'Installez lm-sensors: sudo apt install lm-sensors'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_battery",
        "category": "advanced_system",
        "description": "Affiche les infos batterie/alimentation",
        "triggers": ["info batterie", "état batterie", "batterie", "alimentation"],
        "action_type": "bash",
        "action": "upower -i $(upower -e | grep battery) 2>/dev/null || echo 'Pas de batterie detectee (desktop)'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_kernel",
        "category": "advanced_system",
        "description": "Affiche la version du kernel Linux",
        "triggers": ["version du kernel", "kernel version", "version noyau", "quel kernel"],
        "action_type": "bash",
        "action": "uname -r && uname -v",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_uptime",
        "category": "advanced_system",
        "description": "Affiche le temps de fonctionnement du systeme",
        "triggers": ["uptime", "temps de fonctionnement", "depuis quand le pc tourne"],
        "action_type": "bash",
        "action": "uptime -p && echo 'Boot: ' && uptime -s",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_disk_io",
        "category": "advanced_system",
        "description": "Affiche les statistiques IO disque",
        "triggers": ["io disque", "activité disque", "disk io", "lecture écriture disque"],
        "action_type": "bash",
        "action": "iostat -x 1 1 2>/dev/null || echo 'Installez sysstat: sudo apt install sysstat'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_gpu_status",
        "category": "advanced_system",
        "description": "Affiche l'etat des GPU NVIDIA",
        "triggers": ["état gpu", "gpu status", "nvidia status", "utilisation gpu"],
        "action_type": "bash",
        "action": "nvidia-smi --query-gpu=name,utilization.gpu,memory.used,memory.total,temperature.gpu --format=csv,noheader 2>/dev/null || echo 'nvidia-smi non disponible'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sys_services_failed",
        "category": "advanced_system",
        "description": "Affiche les services systemd en echec",
        "triggers": ["services en échec", "services failed", "services en erreur"],
        "action_type": "bash",
        "action": "systemctl --failed",
        "params": "[]",
        "confirm": 0,
    },

    # ── 5. Reseau avance (10) ──
    {
        "name": "adv_net_who_connected",
        "category": "advanced_network",
        "description": "Affiche qui est connecte au systeme",
        "triggers": ["qui est connecté", "utilisateurs connectés au système", "who is logged in"],
        "action_type": "bash",
        "action": "w",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_bandwidth",
        "category": "advanced_network",
        "description": "Affiche la bande passante par processus",
        "triggers": ["bande passante", "bandwidth", "consommation réseau", "utilisation réseau"],
        "action_type": "bash",
        "action": "sudo nethogs -t -c 3 2>/dev/null || sudo iftop -t -s 3 2>/dev/null || echo 'Installez nethogs: sudo apt install nethogs'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_active_connections",
        "category": "advanced_network",
        "description": "Liste les connexions reseau actives",
        "triggers": ["connexions actives", "connexions réseau", "active connections"],
        "action_type": "bash",
        "action": "ss -tn state established",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_dns_lookup",
        "category": "advanced_network",
        "description": "Effectue une resolution DNS",
        "triggers": ["dns lookup", "résolution dns", "dig", "nslookup"],
        "action_type": "bash",
        "action": "dig google.com +short && echo '---' && cat /etc/resolv.conf | grep nameserver",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_ping_google",
        "category": "advanced_network",
        "description": "Teste la connectivite avec Google",
        "triggers": ["ping google", "teste la connexion", "test internet", "ping"],
        "action_type": "bash",
        "action": "ping -c 4 8.8.8.8",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_public_ip",
        "category": "advanced_network",
        "description": "Affiche l'adresse IP publique",
        "triggers": ["ip publique", "mon ip publique", "adresse ip publique", "public ip"],
        "action_type": "bash",
        "action": "curl -s ifconfig.me && echo ''",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_local_ip",
        "category": "advanced_network",
        "description": "Affiche les adresses IP locales",
        "triggers": ["ip locale", "mon ip locale", "adresse ip locale", "local ip"],
        "action_type": "bash",
        "action": "ip -4 addr show | grep inet | grep -v 127.0.0.1 | awk '{print $NF\": \"$2}'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_speed_test",
        "category": "advanced_network",
        "description": "Teste la vitesse de connexion internet",
        "triggers": ["test de vitesse", "speed test", "vitesse internet", "speedtest"],
        "action_type": "bash",
        "action": "speedtest-cli --simple 2>/dev/null || echo 'Installez speedtest-cli: sudo apt install speedtest-cli'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_route_table",
        "category": "advanced_network",
        "description": "Affiche la table de routage",
        "triggers": ["table de routage", "routes réseau", "routing table"],
        "action_type": "bash",
        "action": "ip route show",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_net_wifi_info",
        "category": "advanced_network",
        "description": "Affiche les infos WiFi",
        "triggers": ["info wifi", "état wifi", "wifi status", "réseau wifi"],
        "action_type": "bash",
        "action": "nmcli dev wifi list 2>/dev/null || iwconfig 2>/dev/null | grep -v 'no wireless'",
        "params": "[]",
        "confirm": 0,
    },

    # ── 6. Audio/Multimedia (10) ──
    {
        "name": "adv_audio_volume_50",
        "category": "advanced_audio",
        "description": "Met le volume a 50 pourcent",
        "triggers": ["volume à 50", "volume à cinquante", "volume 50 pourcent"],
        "action_type": "bash",
        "action": "pactl set-sink-volume @DEFAULT_SINK@ 50%",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_volume_100",
        "category": "advanced_audio",
        "description": "Met le volume au maximum",
        "triggers": ["volume au max", "volume maximum", "volume à 100"],
        "action_type": "bash",
        "action": "pactl set-sink-volume @DEFAULT_SINK@ 100%",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_mute_toggle",
        "category": "advanced_audio",
        "description": "Active ou desactive le son",
        "triggers": ["mute", "coupe le son", "active le son", "toggle mute"],
        "action_type": "bash",
        "action": "pactl set-sink-mute @DEFAULT_SINK@ toggle",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_volume_up",
        "category": "advanced_audio",
        "description": "Augmente le volume de 10 pourcent",
        "triggers": ["monte le volume", "plus fort", "augmente le son", "volume up"],
        "action_type": "bash",
        "action": "pactl set-sink-volume @DEFAULT_SINK@ +10%",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_volume_down",
        "category": "advanced_audio",
        "description": "Diminue le volume de 10 pourcent",
        "triggers": ["baisse le volume", "moins fort", "diminue le son", "volume down"],
        "action_type": "bash",
        "action": "pactl set-sink-volume @DEFAULT_SINK@ -10%",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_screenshot",
        "category": "advanced_audio",
        "description": "Prend une capture d'ecran",
        "triggers": ["capture écran", "screenshot", "prends une capture"],
        "action_type": "bash",
        "action": "gnome-screenshot -f /home/turbo/Images/screenshot_$(date +%Y%m%d_%H%M%S).png && echo 'Capture sauvegardee dans ~/Images/'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_screenshot_area",
        "category": "advanced_audio",
        "description": "Prend une capture d'ecran d'une zone",
        "triggers": ["capture d'une zone", "screenshot zone", "capture sélection"],
        "action_type": "bash",
        "action": "gnome-screenshot -a -f /home/turbo/Images/screenshot_area_$(date +%Y%m%d_%H%M%S).png && echo 'Capture de zone sauvegardee dans ~/Images/'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_record_screen",
        "category": "advanced_audio",
        "description": "Lance l'enregistrement d'ecran",
        "triggers": ["enregistre l'écran", "enregistrement écran", "record screen"],
        "action_type": "bash",
        "action": "gnome-screen-recorder &>/dev/null & || echo 'Utilisez Ctrl+Shift+Alt+R pour enregistrer sous GNOME'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_list_sinks",
        "category": "advanced_audio",
        "description": "Liste les peripheriques audio",
        "triggers": ["périphériques audio", "sorties audio", "liste les sorties son"],
        "action_type": "bash",
        "action": "pactl list sinks short",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_audio_bluetooth_devices",
        "category": "advanced_audio",
        "description": "Liste les appareils bluetooth connectes",
        "triggers": ["appareils bluetooth", "bluetooth connectés", "haut-parleur bluetooth"],
        "action_type": "bash",
        "action": "bluetoothctl devices Connected 2>/dev/null || bluetoothctl paired-devices",
        "params": "[]",
        "confirm": 0,
    },

    # ── 7. Git avance (10) ──
    {
        "name": "adv_git_last_commit",
        "category": "advanced_git",
        "description": "Affiche le dernier commit",
        "triggers": ["dernier commit", "dernier git commit", "last commit"],
        "action_type": "bash",
        "action": "git log -1 --format='%h - %s (%an, %ar)'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_diff_stat",
        "category": "advanced_git",
        "description": "Affiche un resume des changements",
        "triggers": ["diff des changements", "résumé git diff", "git changes"],
        "action_type": "bash",
        "action": "git diff --stat",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_branches",
        "category": "advanced_git",
        "description": "Liste toutes les branches git",
        "triggers": ["branches", "branches git", "liste les branches"],
        "action_type": "bash",
        "action": "git branch -a",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_pull",
        "category": "advanced_git",
        "description": "Telecharge les derniers changements",
        "triggers": ["pull le code", "git pull", "télécharge le code"],
        "action_type": "bash",
        "action": "git pull",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_stash",
        "category": "advanced_git",
        "description": "Met de cote les changements en cours",
        "triggers": ["stash le travail", "git stash", "mets de côté"],
        "action_type": "bash",
        "action": "git stash",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_status",
        "category": "advanced_git",
        "description": "Affiche l'etat du depot git",
        "triggers": ["status git", "état du dépôt", "git status"],
        "action_type": "bash",
        "action": "git status -sb",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_log_graph",
        "category": "advanced_git",
        "description": "Affiche l'historique git en graphe",
        "triggers": ["historique git", "graphe git", "git log graphique"],
        "action_type": "bash",
        "action": "git log --oneline --graph --all -20",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_stash_list",
        "category": "advanced_git",
        "description": "Liste les stashs enregistres",
        "triggers": ["liste des stashs", "stash list", "stashs enregistrés"],
        "action_type": "bash",
        "action": "git stash list",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_stash_pop",
        "category": "advanced_git",
        "description": "Restaure le dernier stash",
        "triggers": ["restaure le stash", "stash pop", "récupère le stash"],
        "action_type": "bash",
        "action": "git stash pop",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_git_remote",
        "category": "advanced_git",
        "description": "Affiche les depots distants configures",
        "triggers": ["remotes git", "dépôts distants", "git remote"],
        "action_type": "bash",
        "action": "git remote -v",
        "params": "[]",
        "confirm": 0,
    },

    # ── 8. Docker/Containers (10) ──
    {
        "name": "adv_docker_ps",
        "category": "advanced_docker",
        "description": "Liste les containers actifs",
        "triggers": ["containers actifs", "docker ps", "containers en cours"],
        "action_type": "bash",
        "action": "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_docker_ps_all",
        "category": "advanced_docker",
        "description": "Liste tous les containers",
        "triggers": ["tous les containers", "docker ps all", "tous les dockers"],
        "action_type": "bash",
        "action": "docker ps -a --format 'table {{.Names}}\\t{{.Status}}\\t{{.Image}}'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_docker_images",
        "category": "advanced_docker",
        "description": "Liste les images Docker",
        "triggers": ["images docker", "docker images", "liste les images"],
        "action_type": "bash",
        "action": "docker images --format 'table {{.Repository}}\\t{{.Tag}}\\t{{.Size}}'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_docker_logs",
        "category": "advanced_docker",
        "description": "Affiche les logs du dernier container",
        "triggers": ["logs container", "docker logs", "logs du container"],
        "action_type": "bash",
        "action": "docker logs --tail 50 $(docker ps -q | head -1) 2>/dev/null || echo 'Aucun container actif'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_docker_restart",
        "category": "advanced_docker",
        "description": "Redémarre tous les containers",
        "triggers": ["restart container", "redémarre les containers", "docker restart all"],
        "action_type": "bash",
        "action": "docker restart $(docker ps -q) 2>/dev/null && echo 'Containers redemarres' || echo 'Aucun container actif'",
        "params": "[]",
        "confirm": 1,
    },
    {
        "name": "adv_docker_prune",
        "category": "advanced_docker",
        "description": "Nettoie les ressources Docker inutilisees",
        "triggers": ["nettoie docker", "docker prune", "clean docker"],
        "action_type": "bash",
        "action": "docker system prune -f",
        "params": "[]",
        "confirm": 1,
    },
    {
        "name": "adv_docker_stats",
        "category": "advanced_docker",
        "description": "Affiche les statistiques des containers",
        "triggers": ["stats docker", "statistiques containers", "docker stats"],
        "action_type": "bash",
        "action": "docker stats --no-stream --format 'table {{.Name}}\\t{{.CPUPerc}}\\t{{.MemUsage}}'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_docker_networks",
        "category": "advanced_docker",
        "description": "Liste les reseaux Docker",
        "triggers": ["réseaux docker", "docker networks", "networks docker"],
        "action_type": "bash",
        "action": "docker network ls",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_docker_volumes",
        "category": "advanced_docker",
        "description": "Liste les volumes Docker",
        "triggers": ["volumes docker", "docker volumes", "stockage docker"],
        "action_type": "bash",
        "action": "docker volume ls",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_docker_disk_usage",
        "category": "advanced_docker",
        "description": "Affiche l'espace disque utilise par Docker",
        "triggers": ["espace docker", "docker disk usage", "taille docker"],
        "action_type": "bash",
        "action": "docker system df",
        "params": "[]",
        "confirm": 0,
    },

    # ── 9. Securite (10) ──
    {
        "name": "adv_sec_last_logins",
        "category": "advanced_security",
        "description": "Affiche les 10 dernieres connexions",
        "triggers": ["dernières connexions", "last logins", "qui s'est connecté"],
        "action_type": "bash",
        "action": "last -10",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_failed_logins",
        "category": "advanced_security",
        "description": "Affiche les tentatives de connexion echouees",
        "triggers": ["tentatives échouées", "failed logins", "connexions échouées"],
        "action_type": "bash",
        "action": "sudo lastb -10 2>/dev/null || echo 'Acces refuse ou lastb non disponible'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_logged_users",
        "category": "advanced_security",
        "description": "Affiche les utilisateurs actuellement connectes",
        "triggers": ["utilisateurs connectés", "who", "qui est connecté maintenant"],
        "action_type": "bash",
        "action": "who -u",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_suid_files",
        "category": "advanced_security",
        "description": "Trouve les fichiers avec permissions SUID",
        "triggers": ["permissions sensibles", "fichiers suid", "fichiers setuid"],
        "action_type": "bash",
        "action": "find /usr -perm -4000 -type f 2>/dev/null | head -20",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_ssh_keys",
        "category": "advanced_security",
        "description": "Liste les cles SSH configurees",
        "triggers": ["clés ssh", "ssh keys", "liste les clés ssh"],
        "action_type": "bash",
        "action": "ls -la ~/.ssh/ 2>/dev/null || echo 'Aucun dossier .ssh'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_open_ports",
        "category": "advanced_security",
        "description": "Liste les ports ouverts avec les processus",
        "triggers": ["ports ouverts détaillés", "ports et processus", "listening ports"],
        "action_type": "bash",
        "action": "sudo ss -tlnp | column -t",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_sudo_log",
        "category": "advanced_security",
        "description": "Affiche les dernieres commandes sudo",
        "triggers": ["historique sudo", "commandes sudo", "sudo log"],
        "action_type": "bash",
        "action": "sudo journalctl _COMM=sudo -n 20 --no-pager",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_check_rootkits",
        "category": "advanced_security",
        "description": "Lance une verification anti-rootkit rapide",
        "triggers": ["scan rootkit", "cherche les rootkits", "check rootkit"],
        "action_type": "bash",
        "action": "sudo chkrootkit -q 2>/dev/null || echo 'Installez chkrootkit: sudo apt install chkrootkit'",
        "params": "[]",
        "confirm": 1,
    },
    {
        "name": "adv_sec_password_policy",
        "category": "advanced_security",
        "description": "Affiche la politique de mots de passe",
        "triggers": ["politique mots de passe", "password policy", "règles mots de passe"],
        "action_type": "bash",
        "action": "sudo chage -l turbo",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_sec_audit_users",
        "category": "advanced_security",
        "description": "Liste les utilisateurs avec shell de connexion",
        "triggers": ["audit utilisateurs", "utilisateurs système", "comptes utilisateurs"],
        "action_type": "bash",
        "action": "awk -F: '$7 !~ /(nologin|false|sync|halt|shutdown)/' /etc/passwd",
        "params": "[]",
        "confirm": 0,
    },

    # ── 10. JARVIS specifique (10) ──
    {
        "name": "adv_jarvis_status",
        "category": "advanced_jarvis",
        "description": "Affiche l'etat de tous les services JARVIS",
        "triggers": ["status jarvis", "état de jarvis", "jarvis status"],
        "action_type": "bash",
        "action": "systemctl --user status jarvis-* --no-pager 2>/dev/null | grep -E '(●|Active:|jarvis)' || echo 'Services JARVIS non trouves'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_restart",
        "category": "advanced_jarvis",
        "description": "Redemarre tous les services JARVIS",
        "triggers": ["redémarre jarvis", "restart jarvis", "relance jarvis"],
        "action_type": "bash",
        "action": "systemctl --user restart jarvis-full.target 2>/dev/null && echo 'JARVIS redémarre' || echo 'Target jarvis-full.target non trouve'",
        "params": "[]",
        "confirm": 1,
    },
    {
        "name": "adv_jarvis_logs",
        "category": "advanced_jarvis",
        "description": "Affiche les 50 derniers logs JARVIS",
        "triggers": ["logs jarvis récents", "journal jarvis récent", "jarvis logs"],
        "action_type": "bash",
        "action": "journalctl --user -u 'jarvis-*' -n 50 --no-pager 2>/dev/null || echo 'Pas de logs JARVIS trouves'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_memory",
        "category": "advanced_jarvis",
        "description": "Affiche la memoire utilisee par JARVIS",
        "triggers": ["mémoire jarvis", "ram jarvis", "jarvis memory usage"],
        "action_type": "bash",
        "action": "ps aux | grep -i jarvis | grep -v grep | awk '{sum+=$6} END {printf \"JARVIS utilise %.1f Mo de RAM\\n\", sum/1024}'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_version",
        "category": "advanced_jarvis",
        "description": "Affiche la version de JARVIS",
        "triggers": ["version jarvis", "jarvis version", "quelle version de jarvis"],
        "action_type": "bash",
        "action": "head -5 /home/turbo/jarvis/CLAUDE.md 2>/dev/null || echo 'Fichier version non trouve'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_db_size",
        "category": "advanced_jarvis",
        "description": "Affiche la taille de la base JARVIS",
        "triggers": ["taille base jarvis", "taille db jarvis", "jarvis database size"],
        "action_type": "bash",
        "action": "ls -lh /home/turbo/jarvis/data/jarvis.db && echo '---' && sqlite3 /home/turbo/jarvis/data/jarvis.db \"SELECT name, COUNT(*) FROM sqlite_master GROUP BY type;\"",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_commands_count",
        "category": "advanced_jarvis",
        "description": "Compte les commandes vocales JARVIS",
        "triggers": ["combien de commandes jarvis", "nombre de commandes vocales", "jarvis commands count"],
        "action_type": "bash",
        "action": "sqlite3 /home/turbo/jarvis/data/jarvis.db \"SELECT category, COUNT(*) FROM voice_commands GROUP BY category ORDER BY COUNT(*) DESC;\"",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_errors",
        "category": "advanced_jarvis",
        "description": "Affiche les erreurs recentes de JARVIS",
        "triggers": ["erreurs jarvis", "jarvis errors", "problèmes jarvis"],
        "action_type": "bash",
        "action": "journalctl --user -u 'jarvis-*' -p err -n 20 --no-pager 2>/dev/null || echo 'Aucune erreur recente'",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_processes",
        "category": "advanced_jarvis",
        "description": "Liste les processus JARVIS actifs",
        "triggers": ["processus jarvis", "jarvis processes", "services jarvis actifs"],
        "action_type": "bash",
        "action": "ps aux | grep -i jarvis | grep -v grep",
        "params": "[]",
        "confirm": 0,
    },
    {
        "name": "adv_jarvis_disk_usage",
        "category": "advanced_jarvis",
        "description": "Affiche l'espace disque utilise par JARVIS",
        "triggers": ["espace jarvis", "taille dossier jarvis", "jarvis disk usage"],
        "action_type": "bash",
        "action": "du -sh /home/turbo/jarvis/ && echo '---' && du -sh /home/turbo/jarvis/*/ 2>/dev/null | sort -h",
        "params": "[]",
        "confirm": 0,
    },
]


def main():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    inserted = 0
    skipped = 0
    errors = 0

    for cmd in ADVANCED_COMMANDS:
        triggers_json = json.dumps(cmd["triggers"], ensure_ascii=False)
        try:
            cursor.execute(
                """INSERT OR IGNORE INTO voice_commands
                   (name, category, description, triggers, action_type, action, params, confirm, enabled, created_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?)""",
                (
                    cmd["name"],
                    cmd["category"],
                    cmd["description"],
                    triggers_json,
                    cmd["action_type"],
                    cmd["action"],
                    cmd["params"],
                    cmd["confirm"],
                    time.time(),
                ),
            )
            if cursor.rowcount > 0:
                inserted += 1
            else:
                skipped += 1
        except sqlite3.Error as e:
            print(f"  ERREUR pour {cmd['name']}: {e}")
            errors += 1

    conn.commit()

    # Verification du total
    total = cursor.execute("SELECT COUNT(*) FROM voice_commands").fetchone()[0]
    adv_count = cursor.execute(
        "SELECT COUNT(*) FROM voice_commands WHERE category LIKE 'advanced_%'"
    ).fetchone()[0]

    # Detail par categorie
    categories = cursor.execute(
        "SELECT category, COUNT(*) FROM voice_commands WHERE category LIKE 'advanced_%' GROUP BY category ORDER BY category"
    ).fetchall()

    conn.close()

    print("=== Insertion des 100 commandes vocales avancees ===")
    print(f"  Inserees  : {inserted}")
    print(f"  Ignorees  : {skipped} (deja presentes)")
    print(f"  Erreurs   : {errors}")
    print(f"  ---")
    print(f"  Commandes avancees par categorie :")
    for cat, count in categories:
        print(f"    {cat}: {count}")
    print(f"  ---")
    print(f"  Total commandes avancees dans la DB : {adv_count}")
    print(f"  Total commandes dans la DB           : {total}")


if __name__ == "__main__":
    main()
