"""JARVIS Auto-Developer — Autonomous code generation pipeline.

Analyzes voice correction logs to find unmatched commands, generates new
JarvisCommand entries via the IA cluster, tests them, and optionally commits.

Usage:
    from src.auto_developer import auto_developer
    await auto_developer.run_cycle()
"""

from __future__ import annotations

import asyncio
import json
import logging
import subprocess
import time
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger("jarvis.autodev")

TURBO_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = TURBO_DIR / "data"


@dataclass
class GapAnalysis:
    """A detected gap in voice command coverage."""
    pattern: str
    count: int
    examples: list[str]
    category: str = "unknown"
    description: str = ""


@dataclass
class GeneratedCommand:
    """A command generated by the IA cluster."""
    name: str
    category: str
    description: str
    triggers: list[str]
    action_type: str
    action: str
    source: str = "auto_developer"
    confidence: float = 0.0
    tested: bool = False


class AutoDeveloper:
    """Pipeline for autonomous command/skill generation."""

    def __init__(self) -> None:
        self._generated: list[GeneratedCommand] = []
        self._cycle_log: list[dict[str, Any]] = []
        self._state_file = DATA_DIR / "autodev_state.json"

    # ── Gap Analysis ──────────────────────────────────────────────────────

    async def analyze_gaps(self, min_count: int = 3) -> list[GapAnalysis]:
        """Identify gaps: voice commands that failed matching repeatedly."""
        gaps: list[GapAnalysis] = []

        # Source 1: voice corrections database
        try:
            import sqlite3
            db_path = DATA_DIR / "jarvis.db"
            if db_path.exists():
                with sqlite3.connect(str(db_path)) as conn:
                    conn.row_factory = sqlite3.Row
                    # Look for low-confidence matches (below 0.5)
                    rows = conn.execute("""
                        SELECT original_text, COUNT(*) as cnt
                        FROM voice_corrections
                        WHERE confidence < 0.5
                        GROUP BY original_text
                        HAVING cnt >= ?
                        ORDER BY cnt DESC
                        LIMIT 20
                    """, (min_count,)).fetchall()

                    for row in rows:
                        gaps.append(GapAnalysis(
                            pattern=row["original_text"],
                            count=row["cnt"],
                            examples=[row["original_text"]],
                            description=f"Commande vocale non reconnue {row['cnt']}x",
                        ))
        except Exception as e:
            logger.debug("Gap analysis (voice_corrections): %s", e)

        # Source 2: event_bus unhandled patterns
        try:
            from src.event_bus import event_bus
            events = event_bus.get_events(limit=200)
            unhandled = [e for e in events if e.get("event", "").startswith("voice.unmatched")]
            if unhandled:
                texts = [e.get("data_keys", [""])[0] for e in unhandled]
                counter = Counter(texts)
                for text, cnt in counter.most_common(10):
                    if cnt >= min_count and text:
                        gaps.append(GapAnalysis(
                            pattern=text, count=cnt, examples=[text],
                            description=f"Pattern vocal non gere {cnt}x",
                        ))
        except Exception as e:
            logger.error(f"Erreur inattendue: {str(e)}")

        # Deduplicate
        seen = set()
        unique: list[GapAnalysis] = []
        for g in gaps:
            key = g.pattern.lower().strip()
            if key not in seen:
                seen.add(key)
                unique.append(g)

        logger.info("Gap analysis: %d gaps found", len(unique))
        return unique[:15]

    # ── Generation ────────────────────────────────────────────────────────

    async def generate_command(self, gap: GapAnalysis) -> GeneratedCommand | None:
        """Generate a new JarvisCommand via the IA cluster."""
        prompt = (
            "Tu es JARVIS, assistant IA Windows. "
            f"L'utilisateur demande souvent: '{gap.pattern}' ({gap.count}x) mais aucune commande ne matche.\n"
            "Genere UNE commande vocale JARVIS en JSON strict:\n"
            '{"name": "string", "category": "string", "description": "string", '
            '"triggers": ["phrase1", "phrase2", "phrase3"], '
            '"action_type": "powershell|hotkey|python|browser|app_open", '
            '"action": "command_to_execute"}\n\n'
            "Categories: navigation, fichiers, systeme, media, app, trading, dev, communication.\n"
            "action_type:\n"
            "- powershell: commande PowerShell Windows\n"
            "- hotkey: raccourci clavier (ex: ctrl+c, win+left)\n"
            "- python: fonction Python (module.function)\n"
            "- browser: navigate:URL ou search:query\n"
            "- app_open: nom d'application\n\n"
            "Reponds UNIQUEMENT avec le JSON."
        )

        # Query M1 cluster
        result = await self._cluster_query(prompt)
        if not result:
            return None

        try:
            # Parse JSON from response
            text = result.strip()
            if "```" in text:
                text = text.split("```")[1]
                if text.startswith("json"):
                    text = text[4:]
                text = text.strip()

            data = json.loads(text)
            cmd = GeneratedCommand(
                name=data.get("name", f"auto_{gap.pattern[:20]}"),
                category=data.get("category", "systeme"),
                description=data.get("description", gap.description),
                triggers=data.get("triggers", [gap.pattern]),
                action_type=data.get("action_type", "powershell"),
                action=data.get("action", ""),
                confidence=0.7,
            )
            self._generated.append(cmd)
            return cmd
        except (json.JSONDecodeError, KeyError) as e:
            logger.warning("generate_command JSON parse failed: %s", e)
            return None

    async def _cluster_query(self, prompt: str) -> str | None:
        """Query the IA cluster for code generation."""
        import httpx

        # Try M1 qwen3-8b first (CHAMPION LOCAL)
        try:
            async with httpx.AsyncClient(timeout=60) as client:
                resp = await client.post(
                    "http://127.0.0.1:1234/api/v1/chat",
                    json={
                        "model": "qwen3-8b",
                        "input": f"/nothink\n{prompt}",
                        "temperature": 0.2,
                        "max_output_tokens": 2048,
                        "stream": False,
                        "store": False,
                    },
                )
                resp.raise_for_status()
                data = resp.json()
                output = data.get("output", [])
                for block in reversed(output):
                    if block.get("type") == "message":
                        return block.get("content", "")
                return output[0].get("content", "") if output else ""
        except Exception as e:
            logger.debug("M1 query failed: %s", e)

        # Fallback: M1/qwen3-8b
        try:
            from src.config import prepare_lmstudio_input, build_lmstudio_payload
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.post(
                    "http://127.0.0.1:1234/api/v1/chat",
                    json=build_lmstudio_payload(
                        "qwen3-8b",
                        prepare_lmstudio_input(prompt, "M1", "qwen3-8b"),
                        max_output_tokens=512,
                    ),
                )
                resp.raise_for_status()
                from src.tools import extract_lms_output
                return extract_lms_output(resp.json())
        except Exception as e:
            logger.debug("M1 query failed: %s", e)
            return None

    # ── Testing ───────────────────────────────────────────────────────────

    async def test_generated(self, cmd: GeneratedCommand) -> bool:
        """Test a generated command (dry run validation)."""
        # Validate structure
        if not cmd.name or not cmd.triggers or not cmd.action:
            return False
        if cmd.action_type not in ("powershell", "hotkey", "python", "browser", "app_open", "bash",
                                    "ms_settings", "pipeline", "script"):
            return False
        if len(cmd.triggers) < 1:
            return False

        # Check for dangerous patterns
        dangerous = ["rm -rf", "format", "del /s", "Remove-Item -Recurse -Force C:\\",
                      "shutdown", "restart", "Stop-Computer"]
        for d in dangerous:
            if d.lower() in cmd.action.lower():
                logger.warning("Dangerous action rejected: %s", cmd.action[:50])
                return False

        cmd.tested = True
        return True

    # ── Registration ──────────────────────────────────────────────────────

    def _register_command(self, cmd: GeneratedCommand) -> bool:
        """Register a generated command into the runtime command list."""
        try:
            from src.commands import COMMANDS, JarvisCommand
            # Check for name collision
            existing_names = {c.name for c in COMMANDS}
            if cmd.name in existing_names:
                cmd.name = f"auto_{cmd.name}"
                if cmd.name in existing_names:
                    return False

            jcmd = JarvisCommand(
                name=cmd.name,
                category=cmd.category,
                description=cmd.description,
                triggers=cmd.triggers,
                action_type=cmd.action_type,
                action=cmd.action,
            )
            COMMANDS.append(jcmd)
            logger.info("Auto-registered command: %s (%d triggers)", cmd.name, len(cmd.triggers))
            return True
        except Exception as e:
            logger.warning("register_command failed: %s", e)
            return False

    # ── Git commit ────────────────────────────────────────────────────────

    async def commit_to_git(self, files: list[str], message: str) -> dict[str, Any]:
        """Auto-commit generated files."""
        try:
            # Stage files
            r = await asyncio.to_thread(
                subprocess.run,
                ["git", "add"] + files,
                capture_output=True, text=True, timeout=10,
                cwd=str(TURBO_DIR),
            )
            if r.returncode != 0:
                return {"error": f"git add failed: {r.stderr}"}

            # Commit
            r = await asyncio.to_thread(
                subprocess.run,
                ["git", "commit", "-m", f"[autodev] {message}"],
                capture_output=True, text=True, timeout=10,
                cwd=str(TURBO_DIR),
            )
            return {"committed": r.returncode == 0, "output": r.stdout[:200]}
        except Exception as e:
            return {"error": str(e)}

    # ── Full Cycle ────────────────────────────────────────────────────────

    async def run_cycle(self, max_gaps: int = 5) -> dict[str, Any]:
        """Full cycle: analyze gaps → generate → test → register."""
        cycle_start = time.time()
        report: dict[str, Any] = {"gaps": 0, "generated": 0, "tested": 0, "registered": 0, "errors": []}

        gaps = await self.analyze_gaps()
        report["gaps"] = len(gaps)

        for gap in gaps[:max_gaps]:
            try:
                cmd = await self.generate_command(gap)
                if not cmd:
                    continue
                report["generated"] += 1

                if await self.test_generated(cmd):
                    report["tested"] += 1
                    if self._register_command(cmd):
                        report["registered"] += 1
                        # Emit event
                        try:
                            from src.event_bus import event_bus
                            await event_bus.emit("autodev.command_created", {
                                "name": cmd.name, "triggers": cmd.triggers[:3],
                            })
                        except Exception as e:
                            report["errors"].append(f"{str(e)[:100]} (caught in inner block)")
            except Exception as e:
                report["errors"].append(str(e)[:100])

        report["duration_s"] = round(time.time() - cycle_start, 1)
        self._cycle_log.append({"ts": time.time(), **report})

        # Save state
        self._save_state()

        logger.info("AutoDev cycle: %d gaps → %d generated → %d registered (%.1fs)",
                     report["gaps"], report["generated"], report["registered"], report["duration_s"])
        return report

    def _save_state(self) -> None:
        """Persist state to disk."""
        state = {
            "generated_count": len(self._generated),
            "last_cycle": self._cycle_log[-1] if self._cycle_log else None,
            "total_cycles": len(self._cycle_log),
        }
        try:
            DATA_DIR.mkdir(parents=True, exist_ok=True)
            self._state_file.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")
        except Exception as e:
            logger.debug("save_state failed: %s", e)

    def get_stats(self) -> dict[str, Any]:
        """AutoDeveloper stats."""
        return {
            "generated_commands": len(self._generated),
            "total_cycles": len(self._cycle_log),
            "last_cycle": self._cycle_log[-1] if self._cycle_log else None,
        }


# Global singleton
auto_developer = AutoDeveloper()
